# app/universe/kompas100_full.py

KOMPAS100 = [
    # BANK & FINANCE
    "BBCA.JK","BBRI.JK","BMRI.JK","BBNI.JK","BRIS.JK",
    "BNGA.JK","MEGA.JK","BJBR.JK","BJTM.JK","PNBN.JK",

    # TELEKOMUNIKASI & TECHNOLOGY
    "TLKM.JK","EXCL.JK","ISAT.JK","GOTO.JK","ARTO.JK",
    "BUKA.JK","DCII.JK",

    # ENERGY & MINING
    "ADRO.JK","ANTM.JK","MDKA.JK","INCO.JK","TINS.JK",
    "PTBA.JK","ITMG.JK","HRUM.JK","BRMS.JK","BUMI.JK",
    "INDY.JK","MBAP.JK","TOBA.JK",

    # OIL & GAS
    "PGAS.JK","AKRA.JK","MEDC.JK","ELSA.JK","RAJA.JK",

    # CONSUMER GOODS
    "ICBP.JK","INDF.JK","UNVR.JK","MYOR.JK","KLBF.JK",
    "SIDO.JK","CPIN.JK","JPFA.JK","GGRM.JK","HMSP.JK",

    # RETAIL & LIFESTYLE
    "MAPI.JK","ACES.JK","ERAA.JK","AMRT.JK","RALS.JK",

    # PROPERTY & REAL ESTATE
    "CTRA.JK","BSDE.JK","PWON.JK","SMRA.JK","ADHI.JK",
    "WIKA.JK","PTPP.JK",

    # INDUSTRIAL & INFRASTRUCTURE
    "ASII.JK","UNTR.JK","JSMR.JK","WTON.JK",

    # TOWER & DATA
    "TBIG.JK","TOWR.JK",

    # MEDIA & TRANSPORT
    "SCMA.JK","MNCN.JK","WEGE.JK",

    # CEMENT & MATERIAL
    "SMGR.JK","INTP.JK","INKP.JK","TKIM.JK",

    # HEALTHCARE
    "MIKA.JK","SILO.JK","KAEF.JK","KLBF.JK",

    # MISC
    "MAPA.JK","AUTO.JK","HEAL.JK","ESSA.JK","FREN.JK",
]
